name = input("Etunimi: ")
lastname = input("Sukunimi: ")
address = input("Katuosoite: ")
zip_and_city = input("Postinumero ja kaupunki: ")
print(name + " " + lastname)
print(address)
print(zip_and_city)